### ISSUE TITLE
Update VT trace reader to support new format with migratable and non-migratable objects

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#102]
* migratable objects should be stored as `migratable` using `add_migratable_object`
* non-migratable objects should be stored as `sentinel` using `add_sentinel_object`

**Comment by marcinwrobel1986** [comment]
Hi @ppebay I have noticed a bug in class `Processor` in `__init__` instead of:
```Python
self.add_sentinel(o)
```
should be:
```Python
self.add_sentinel_object(o)
```

**Comment by marcinwrobel1986** [comment]
@ppebay  I added support for reading the new format. Is that it in this task?
