### ISSUE TITLE
Create generic functions to print messages, warnings, errors, in standardized way.

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#132]
We should have a helper function called `print_error()`, another one called `print_warning()` and yet another one called `print_message()` that would generically deal with the properly-colored headings. In addition I would make the warnings have an orange-colored heading, the regular messages have a green heading (and keep the red for errors).

I would create a `lbsPrint.py` in `IO` with just the corresponding **static** functions.

**Comment by PhilMiller** [comment]
There are widely used libraries to handle this, and which offer much more in the way of configuration.

I think in python it's 'logging', but I'd have to look

**Comment by marcinwrobel1986** [comment]
> There are widely used libraries to handle this, and which offer much more in the way of configuration.
> 
> I think in python it's 'logging', but I'd have to look

Yes, it is `logging` in Python

**Comment by marcinwrobel1986** [comment]
@ppebay Philippe what are we doing with all the `Viewers` in `src/Applications`? Do we keep them? Does anyone use them? Are they working?

**Comment by ppebay** [comment]
@marcinwrobel1986 they are used for debugging purposes only (in summary this is to track how well information propagates through the graph during the information phase).
