### ISSUE TITLE
Check logging levels of logger

### ISSUE THREAD

**Issue by marcinwrobel1986** [DARMA-tasking/LB-analysis-framework#145]
### TODO:
- check if logging levels work as they supposed to work
- check if logging level is correctly setup

**Comment by ppebay** [comment]
@marcinwrobel1986 I would also like to switch the order of the coloring: it's the heading (e.g., `[lbsRuntime]`) that should have the corresponding info level color (green, etc.), but the text following it should not be colored.

**Comment by marcinwrobel1986** [comment]
I am afraid I do not have such power. I can investigate that. But I would have to overwrite the logger Class from standard library, because user has by default control over the message part ....

**Comment by ppebay** [comment]
I don't quite understand: the heading itself is part of the message, isn't it?

**Comment by marcinwrobel1986** [comment]
No, please take a look at `logger.ini` in `src/Utils` how formatters are defined at the bottom.
So, e.g.:
```ini
[formatter_extend]
format=%(levelname)s [%(module)s.%(funcName)s()] msg:[%(message)s]
```
We have control only over: `%(message)s` - this is what we pass to logger

In PPP formatter:
```ini
[formatter_ppp]
format=[%(module)s] %(message)s
```
We pass only `%(message)s` and you want to modify `[%(module)s]` this can not be done easily. I would need to modify the logger class for that.
Is it clear now?

**Comment by ppebay** [comment]
ok
