### ISSUE TITLE
Create object-based ExodusII output

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#156]
This should be done **in addition** to the existing rank-based output, **not** in its stead.

The goal would be to be able to show essentially the following:
![143924464-51667dfb-28ee-421d-ac58-5c14b1ed9dc0](https://user-images.githubusercontent.com/17439260/152226237-11883d25-ce5d-4f13-ba6a-335f6bd6c384.jpg)
**but** keeping our current approach of storing only the edge with maximum volume when there is one in each direction between two endoints.

**Comment by distractor** [comment]
Not finished, but wrapped up.
@ppebay @marcinwrobel1986

**Comment by ppebay** [comment]
@marcinwrobel1986 , @distractor won't have time to finish it this month.
Can you please pick up the issue and the branch from its current status?
Thanks

**Comment by ppebay** [comment]
Resolved by #245

**Comment by ppebay** [comment]
Resolved by PR #245
