### ISSUE TITLE
Make the rank-object-enumerator app use the conf.yaml file

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#157]
Instead of taking as input a hard-coded block as is currently the case:
```
# Dictionary of objects
objects = (
    {"id": 0, "time": 1.0, "from": {}, "to": {5: 2.0}},
    {"id": 1, "time": 0.5, "from": {4: 2.0}, "to": {4: 1.0}},
    {"id": 2, "time": 0.5, "from": {3: 1.0}, "to": {}},
    {"id": 3, "time": 0.5, "from": {}, "to": {2: 1.0, 8: 0.5}},
    {"id": 4, "time": 0.5, "from": {1: 1.0}, "to": {1: 2.0}},
    {"id": 5, "time": 2.0, "from": {0: 2.0}, "to": {8: 2.0}},
    {"id": 6, "time": 1.0, "from": {7: 1.0, 8: 1.5}, "to": {}},
    {"id": 7, "time": 0.5, "from": {}, "to": {6: 1.0}},
    {"id": 8, "time": 1.5, "from": {3: 0.5, 5: 2.0}, "to": {6: 1.5}})

# Define number of ranks
n_ranks = 4

# Define work constants
alpha = 1.
beta = 1.
gamma = 0.
```
the `rank-object-enumerator.py` script (in `Applications`) should read `conf.yaml` and retrieve:
* `x_procs`, `y_procs`, and `z_procs`, from which it would compute `n_ranks` (the product of these 3 values);
* `alpha`, `beta`, `gamma` (and use them as such);
* `log_file`, `file_suffix`, and `phase_id` to retrieve the objects and their communications from VT trace data.

**Comment by ppebay** [comment]
@marcinwrobel1986 you forgot a small detail... data is to be read from the file and not hard-coded as such:
```
# Dictionary of objects
objects = (
    {"id": 0, "time": 1.0, "from": {}, "to": {5: 2.0}},
    {"id": 1, "time": 0.5, "from": {4: 2.0}, "to": {4: 1.0}},
    {"id": 2, "time": 0.5, "from": {3: 1.0}, "to": {}},
    {"id": 3, "time": 0.5, "from": {}, "to": {2: 1.0, 8: 0.5}},
    {"id": 4, "time": 0.5, "from": {1: 1.0}, "to": {1: 2.0}},
    {"id": 5, "time": 2.0, "from": {0: 2.0}, "to": {8: 2.0}},
    {"id": 6, "time": 1.0, "from": {7: 1.0, 8: 1.5}, "to": {}},
    {"id": 7, "time": 0.5, "from": {}, "to": {6: 1.0}},
    {"id": 8, "time": 1.5, "from": {3: 0.5, 5: 2.0}, "to": {6: 1.5}})
```
Cf. original description of issue.

**Comment by marcinwrobel1986** [comment]
> @marcinwrobel1986 you forgot a small detail... data is to be read from the file and not hard-coded as such:
> 
> ```
> # Dictionary of objects
> objects = (
>     {"id": 0, "time": 1.0, "from": {}, "to": {5: 2.0}},
>     {"id": 1, "time": 0.5, "from": {4: 2.0}, "to": {4: 1.0}},
>     {"id": 2, "time": 0.5, "from": {3: 1.0}, "to": {}},
>     {"id": 3, "time": 0.5, "from": {}, "to": {2: 1.0, 8: 0.5}},
>     {"id": 4, "time": 0.5, "from": {1: 1.0}, "to": {1: 2.0}},
>     {"id": 5, "time": 2.0, "from": {0: 2.0}, "to": {8: 2.0}},
>     {"id": 6, "time": 1.0, "from": {7: 1.0, 8: 1.5}, "to": {}},
>     {"id": 7, "time": 0.5, "from": {}, "to": {6: 1.0}},
>     {"id": 8, "time": 1.5, "from": {3: 0.5, 5: 2.0}, "to": {6: 1.5}})
> ```
> 
> Cf. original description of issue.
> 
> I am using the already-merged changes you made for the 2 other points (which are already very useful); please create new PR for the remaining bit. Thanks

This is why I created a draft PR and ask you if there is anything to add :)

**Comment by ppebay** [comment]
Well yes the first bullet of the original issue ;)

I have added some other features to the rank enumerator, hopefully I did not create a conflict with a local branch you might already have started.
