### ISSUE TITLE
Change factory method to be static members of base classe

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#16]
This will result in removal of `lbsCriterion` helper class and its replacement by a call on the factory method on the base class in the `lbsRuntime`.

**Comment by yaleLeeNGA** [comment]
Criterion factory has been moved to the base class to remove `lbsCriterion`. The factory is called from `lbsRuntime`.  
NodeGossiper is working in this new configuration for all Grapevine, modified Grapevine and Relaxed Localizing criteria.  

N.B.: The branch has been rebased on the top of [branch 17](https://github.com/DARMA-tasking/LB-analysis-framework/issues/17) to use generated views for before/after comparison.
