### ISSUE TITLE
Have the rank object enumerator use the output_dir configuration variable

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#170]
Currently, `optimal-arrangements.csv` is saved in the current exec dir. 

Instead, `rank-object-enumerator.py` should read the value of `output_dir` in the configuration file and store its output inside it.

**Comment by marcinwrobel1986** [comment]
Hi Philippe @ppebay ,
this is already implemented. I mean I added that as it was natural thing to do.
Please take a look [here](https://github.com/DARMA-tasking/LB-analysis-framework/blob/develop/src/Applications/rank_object_enumerator.py#L203-L211)

**Comment by ppebay** [comment]
Here are the steps I am taking:
```
 python rank-object-enumerator.py
alpha: 1.0
beta: 1.0
gamma: 0.0
Initial arrangement: (0, 0, 0, 0, 1, 1, 1, 1, 2)
	per-rank works: {0: 6.0, 1: 8.5, 2: 4.0}
	maximum work: 8.5 average work: 6.167
Number of generated arrangements: 262144
	minimax work: 4 for 24 arrangements
Wrote 24 optimal arrangement to optimal-arrangements.csv
```
and yet, the output file is in the current directory:
```
ls -al *csv
-rw-r--r--  1 pppebay  staff  456 Feb 14 15:55 optimal-arrangements.csv
```
although the configuration file has `output_dir: output` and yet:
```
ls -al output/*csv
zsh: no matches found: output/*csv
```
Are you certain that your implementation made its way into `develop`?

**Comment by marcinwrobel1986** [comment]
@ppebay Philippe please pull the develop and I change name to `rank_object_enumerator.py` to follow naming convention

**Comment by marcinwrobel1986** [comment]
Hi @ppebay, you can pull the latest changes from develop and check it out. Should be ok, and we could close this issue.

**Comment by ppebay** [comment]
Resolved
