### ISSUE TITLE
Newer VTK pypi package versions cause error in lbsWriterExodusII.py

### ISSUE THREAD

**Issue by marcinwrobel1986** [DARMA-tasking/LB-analysis-framework#175]
### What is wrong?
- VTK pypi package newer than 9.0.1 cause `lbsWriterExodusII.py` to fail

### Where in the code is this happenning?
- This is happenning [at line 192 in lbsWriterExodusII.py](https://github.com/DARMA-tasking/LB-analysis-framework/blob/9c7ddad98277259d1957d79207bee3be76a2c489/src/IO/lbsWriterExodusII.py#L192)

### Last good `vtkExodusIIWriter` value before crash (when using VTK > 9.0.1):
```shell
vtkPExodusIIWriter (0x3413f90)
  Debug: Off
  Modified Time: 1178
  Reference Count: 2
  Registered Events: (none)
  Executive: 0x3406650
  ErrorCode: Success
  Information: 0x3413bc0
  AbortExecute: Off
  Progress: 0
  Progress Text: (None)
  FileName output/output_file.e
  StoreDoubles -1
  GhostLevel 0
  WriteOutBlockIdArray 0
  WriteOutGlobalNodeIdArray 0
  WriteOutGlobalElementIdArray 0
  WriteAllTimeSteps 1
  BlockIdArrayName (none)
  ModelMetadata (none)
  IgnoreMetaDataWarning 0
```

### Last good `vtkExodusIIWriter` value before crash (when using VTK == 9.0.1):
```shell
vtkExodusIIWriter (0x38c48d0)
  Debug: Off
  Modified Time: 1600
  Reference Count: 2
  Registered Events: (none)
  Executive: 0x38b6f90
  ErrorCode: Success
  Information: 0x38c47d0
  AbortExecute: Off
  Progress: 0
  Progress Text: (None)
  FileName output/output_file.e
  StoreDoubles 1
  GhostLevel 0
  WriteOutBlockIdArray 0
  WriteOutGlobalNodeIdArray 0
  WriteOutGlobalElementIdArray 0
  WriteAllTimeSteps 1
  BlockIdArrayName (none)
  ModelMetadata 
    Debug: Off
    Modified Time: 1599
    Reference Count: 1
    Registered Events: (none)
    Title: Created by vtkExodusIIWriter, Tue Feb 15 09:24:10 2022

    NumberOfInformationLines: 0
    Dimension: 3
    CoordinateNames: 
    -X
    -Y
    -Z
    NumberOfBlocks: 1
    NumberOfNodeSets: 0
    NodeSetNames:     NodeSetIds: 
    NodeSetNodeIdList: 
    NodeSetDistributionFactors: 
    NumberOfSideSets: 0
    SideSetNames:     SideSetIds: 
    SideSetElementList: 
    SideSetSideList: 
    SideSetNumDFPerSide: 
    SideSetDistributionFactors: 
    NumberOfBlockProperties: 0
    BlockPropertyNames:     NumberOfNodeSetProperties: 0
    NodeSetPropertyNames:     NumberOfSideSetProperties: 0
    SideSetPropertyNames:     NumberOfElementVariables: 1
    ElementVariableNames:     -Largest Directed Volume
    NumberOfNodeVariables: 2
    NodeVariableNames:     -Load
    -Work
    TimeStepIndex: -1
    AllVariablesDefinedInAllBlocks: 0
  IgnoreMetaDataWarning 0
```

### What was observed/hints:
- It looks definately that something was change in `ModelMetadata` of `vtk.vtkExodusIIWriter`
- in version 9.0.1 `ModelMetadata` is not None and definiately consist some data
- error which is printed to the console is `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`
- just from the error message one could take a hint, that is probably to the fact, that file which is already open is trying to be open again
- `MoveCountsViewer.py` was not effected
- the assignee should take a look how files are open/created and how  `lbsWriterExodusII.py` is writing to a files

### How to reproduce the error?
- just install `vtk` grater than 9.0.1 and run `LBAF.py`

**Comment by marcinwrobel1986** [comment]
I have found release notes for 9.0.2:
[9.0.2 release notes](https://discourse.vtk.org/t/vtk-9-0-2/6107)
Apart from that the last step I was able to get into with debugger was at the end of `GridStreamer` then by the end of `lbsWriterExodusII` on `writer.Update()` it breaks with:
```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```
I turn on the debug with `DebugOn()`, but it has not print anything.
@ppebay any ideas

**Comment by marcinwrobel1986** [comment]
Hello @ppebay ,
I spent some time today on that, but I think it is not possible to find the difference.
Why?
- Current working VTK version in Python 3.8 is 9.0.1
- Below sizes of this package for different platforms:
![Zrzut ekranu z 2022-04-01 15-39-27](https://user-images.githubusercontent.com/47597569/161275032-91e1e7a3-9b87-46e2-b64c-9a29f06e309d.png)

- Version 9.0.2 which should differ just a bit from 9.0.1, right?
- Below sizes of this package for different platforms:
![Zrzut ekranu z 2022-04-01 15-39-49](https://user-images.githubusercontent.com/47597569/161275231-2bf34cc3-427c-4eb2-8caf-309257d95e2b.png)

Please look at the difference in sizes between 9.0.1 and 9.0.2 this is crazy. For my use case **9.0.1 has 103.4 MB** and **9.0.2 has 59.5 MB**.
I think the only solution so we have working version of LBAF for Python 3.9 is to do once again the very bottom of `lbsWriterExodusII.py`, because this is a place where we have a problem.
Once that is solved we will have acceptance tests for 3.9 working as well as we could prepare a package for Python 3.9

**Comment by ppebay** [comment]
Re-opening so we keep track of the VTK issue here

**Comment by lifflander** [comment]
https://gitlab.kitware.com/vtk/vtk/-/issues/18862#note_1344338

**Comment by ppebay** [comment]
After discussions, this issue is closed because the visualizer will no longer use Python VTK
