### ISSUE TITLE
Modify MoveCountsViewer to take parameters as command line arguments

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#18]
The goal of this issue is to replace all hard-coded parameter settings in this utility, such as:  
```
# Number of processors
n_p = 8
```
or 
```
file_name = "NodeGossiper-n8-lstats-i5-k4-f4-t1_0.0.{}.vom".format(i)
```
with command-line arguments (e.g., `-i <input-VOM-prefix> -p <number-of-processors>`).

**Comment by yaleLeeNGA** [comment]
MoveCountsViewer now parses following arguments:
- `-p`: number of processors
- `-f`: input file name
- `-s`: input file format suffix (`.vom` by default)
- `-o`: output file name (equal to input file name y default)
- `-t`: output file format suffix (`.png` by default)
- `-i`: interactive call (`False` by default)
a. An interactive call opens a render window as usual, with inherent handlers. 
b. A non-interactive call automatically saves a png image of the render -- with an alpha channel. Such visual can be generated: 
![ex](https://user-images.githubusercontent.com/54635963/65898186-4520ba00-e3b1-11e9-85b4-e673ac87a862.png)


A MoveCountsViewerParameters class has been implemented in so-called script to define viewer parameters at a same place. 

N.B.: For some reason, the actor vertices do not seem to appear on the png generation -- stil appears in the interactive window.

**Comment by yaleLeeNGA** [comment]
Considering actor vertices, corresponding glyphs *are* plotted but **need rescaling** through `SetScreenSize`, all the more that their opacity is not full. 
BUT this glyph rescale solution makes the picture shrink within defined image size as illustrated below:  
![stats](https://user-images.githubusercontent.com/54635963/66033019-bb830080-e506-11e9-9789-b8ff8cdfa05e.png)

**Comment by yaleLeeNGA** [comment]
Considering **Object Moves scale**:  

The bug was due to an uproper actor bar height value -- typo from relocation of viewer setting values defined within `MoveCountsViewer` computation *to* dedicated `MoveCountsViewerParameters` class. This has been fixed, along with formatting all double values in `MoveCountsViewerParameters` class.

**Comment by yaleLeeNGA** [comment]
### Final visual aspect

- in **interactive mode**: 
![stats_interactive](https://user-images.githubusercontent.com/54635963/66038804-6b5e6b00-e513-11e9-8963-dba69bc99703.png)

- in **non-interactive mode**:
1. Image file is automatically saved using `png` format.  
2. Alpha channel is set on.  
N.B.: As mentioned [here](https://github.com/DARMA-tasking/LB-analysis-framework/issues/18#issuecomment-537411203), the figure is not rescaled to fit the whole image dimensions. 
![stats](https://user-images.githubusercontent.com/54635963/66038840-8630df80-e513-11e9-9a20-5ec505ce6ce5.png)

**Comment by lifflander** [comment]
I just saw these graphics for the first time! This is really cool :)
