### ISSUE TITLE
CI test is failing

### ISSUE THREAD

**Issue by marcinwrobel1986** [DARMA-tasking/LB-analysis-framework#185]
### What is the problem:
- the problem is that the CI is failing, but the config file for testing has not changed, this means that probably wrong code was merged to develop

### Where is config file for testing:
- the file is in `scripts/test_config/conf.yaml`

### What test does?
```python3
import sys


def run_tests():
    imbalance_file = f"/lbaf/output/imbalance.txt"
    with open(imbalance_file, 'r') as imb_file:
        imb_level = float(imb_file.read())
        if imb_level < 0.000001:
            print(f"===> TEST PASSED!")
        else:
            print(f"===> TEST FAILED!")
            sys.exit(1)


if __name__ == "__main__":
    run_tests()
```

`imbalance.txt` is saved in `print_function_statistics` in `src/IO/lbsStatistics.py` line: 201

### How it was before:
- before imbalance was 0
- now imbalance is 0.75

**Comment by ppebay** [comment]
Should be resolved by now in #181
<img width="887" alt="Screen Shot 2022-02-21 at 7 53 36 PM" src="https://user-images.githubusercontent.com/17439260/155012379-1f824bcb-c7a2-41cf-8bc2-b3afec1babcd.png">

Please verify
