### ISSUE TITLE
Implement "Work" in objective function

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#19]
This is to integrate in the same concept both notions of Load and Communications and provide a unified framework.

@lifflander

**Comment by ppebay** [comment]
@lifflander

**Comment by PhilMiller** [comment]
The Work notion has to be pretty nuanced if you're going to make a combined
metric. It ends up being some transformation from a (load, messages, bytes)
vector to a (cpu time, network injection time, network transfer time)
vector), over which you then want to minimize the infinity-norm across
processes. Optimising for locality adds additional wrinkles to that, of
course.
