### ISSUE TITLE
Extract a subset of phases from the new dataset and store them as one new LBAF example

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#192]
@lifflander said the new dataset has about 1000 phases resulting in a ~10MB file.

It thus seems reasonable to create a subset with about 10 phases hereby resulting in a ~100kB file. We could e.g. extract phases 1, 101, 201, 301, 401, 501, 601, 701, 801, and 901.

**Comment by marcinwrobel1986** [comment]
There are 32 files 1.1 MB (compressed) each. Each file has 1000 phases, so if we take just 10 phases from from each of 32 files, then each file would have ca. 11kB

@ppebay Please specify if I should extract more phases. Thanks!
