### ISSUE TITLE
Investigate differences between local and GitHub run

### ISSUE THREAD

**Issue by marcinwrobel1986** [DARMA-tasking/LB-analysis-framework#195]
### TODO:
- there are differences between local and GitHub run
- they should be investigated
- both runs on test config: `<LB-analysis-framework>/config/conf.yaml`

File from local run:
[local.txt](https://github.com/DARMA-tasking/LB-analysis-framework/files/8142843/local.txt)

File from GitHub run:
[github.txt](https://github.com/DARMA-tasking/LB-analysis-framework/files/8142845/github.txt)

Assignee could check the differences by doing the simulation both on GH and local. Files and screenshots attached for reference.

![001](https://user-images.githubusercontent.com/47597569/155753031-65577999-f21f-4456-904b-04111f0ad8b8.png)
![002](https://user-images.githubusercontent.com/47597569/155753048-b571e922-e797-4101-bd42-4dddfa9fb435.png)
![003](https://user-images.githubusercontent.com/47597569/155753053-93934caf-c122-49ad-b4c7-08349966cb15.png)
![004](https://user-images.githubusercontent.com/47597569/155753066-54e85dac-6e85-4da8-87b6-72a9fa98c2a7.png)
![005](https://user-images.githubusercontent.com/47597569/155753075-d0c740e7-fab2-4941-9ee8-00690e3c4baf.png)

**Comment by ppebay** [comment]
Got it. Thanks @marcinwrobel1986

**Comment by tlamonthezie** [comment]
Hello @ppebay @lifflander Here are the differences that I can observe from a run on current develop.

- On the left LBAF is run on Ubuntu(Gitbub) from /home/runner/work/LB-analysis-framework/LB-analysis-framework/
- On the right LFAF runs locally on Ubuntu(WSL) from /home/thomas/repositories/LB-analysis-framework/
- Python version 3.8.17 is used on both sides
- The output has exactly the same number of lines (contrary to was shown in previous comments)
- No differences except for [lbsInformAndTransferAlgorithm] for **proposed**, **occured** and **rejected** trasnsfers and also the **skipped ranks.**
- The [lbsInformAndTransferAlgorithm] output is exactily the same on both sides.  (contrary to was shown in previous comments)
All the differences are shown in the screenshots below and are only for the [lbsInformAndTransferAlgorithm] : the number of **proposed**, **occured** and **rejected** trasnsfers and also the **skipped ranks.** in the algorithm iterations

@ppebay This is not very different. It seems that the previous comments are no more applicable. That said is this normal to have differences inside the InformAndTransferAlgorithm iterations ?

![image](https://github.com/DARMA-tasking/LB-analysis-framework/assets/20086568/5df86af0-4044-418f-9f76-1c2b7fd75513)

![image](https://github.com/DARMA-tasking/LB-analysis-framework/assets/20086568/a9be3949-c0b1-49e2-b5a2-1312c38cc406)

![image](https://github.com/DARMA-tasking/LB-analysis-framework/assets/20086568/b5cccb85-807b-4ec5-b19a-1065db409c6a)

**Comment by ppebay** [comment]
This is fixed by #375
