### ISSUE TITLE
Unit test I/O methods

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#201]
Please @marcinwrobel1986 come up with ideas here that we can discuss further here

**Comment by marcinwrobel1986** [comment]
I don't think so. We have currently ca. 30% covered. We could keep that open for adding more test when there is possibility.

**Comment by ppebay** [comment]
Please @tlamonthezie review code coverage level thanks

**Comment by ppebay** [comment]
This has been superseded by #355 and resolved by #389
