### ISSUE TITLE
Report in info mode when more than one object is passed at once

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#215]
In `lbsRuntime.py`, line 341:
```
self.lgr.debug(f"Transferring {len(object_list)} object(s) at once")
```
In addition, we should always report in `info` mode the largest number of objects transferred **at once** at the end of the transfer phase.

Also, we need to eliminate the second return variable `n_o` of `recursive_extended_search()`:
```
return True, n_o
```
which does not seem to be used when the function is invoked:
```
success, _ = self.recursive_extended_search(
```
Please verify this and remove as part of same issue. Tx

**Comment by marcinwrobel1986** [comment]
@ppebay the funny thing is when I do that, I am getting imbalance equal to 0.25 or 0.5 or 0.75 or 1.0 depends on the run. I might to change the bool value to something different and try once again as I do not have any other idea what might caused the problem.

**Comment by marcinwrobel1986** [comment]
Ok, found and eliminated.
