### ISSUE TITLE
Add new data to the repository

### ISSUE THREAD

**Issue by marcinwrobel1986** [DARMA-tasking/LB-analysis-framework#218]
### TODO:
- extract phases and add data to the repository

**Comment by ppebay** [comment]
Isn't this closed by #219?

If so there should be `fixes #218` in PR219 @marcinwrobel1986

**Comment by marcinwrobel1986** [comment]
But there is Closes #218

![Zrzut ekranu z 2022-03-31 10-14-49](https://user-images.githubusercontent.com/47597569/161009436-178259af-bc53-4465-863f-a6bd7c13e450.png)

**Comment by ppebay** [comment]
Do you know why it was not closed automatically then?
