### ISSUE TITLE
Ensure that pre-merge CI actions are on-par with VT ones

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#220]
This issue is to ensure that the LBAF repo has policies consistent with the overall DARMA repo policies, in particular (but not limited to):
- [x] consistent PR description formatting with the policies enforced for VT
- [x] update wiki accordingly

**Comment by ppebay** [comment]
Acknowledged. Thanks.

**Comment by marcinwrobel1986** [comment]
@ppebay I think I have done all for this part of the project. I would say we probably change/adjust things in the future, but for now it should be good.

**Comment by ppebay** [comment]
Worth revisiting

**Comment by lifflander** [comment]
We can just copy the github actions from the template repository: https://github.com/DARMA-tasking/template-repository
