### ISSUE TITLE
Overhaul LBAF algorithms and statistics framework & update lbsStrictLocalizingCriterion

### ISSUE THREAD

**Issue by marcinwrobel1986** [DARMA-tasking/LB-analysis-framework#231]
### TODO:
- `StrictLocalizingCriterion` is not updated as `TemperedCriterion` and does not work

Issue **TODO** expanded by @ppebay to include several other aspects such as:
* generalizing of the global statistics selection and mapping to respective computation methods
* formatting/documentation of algorithms that is not always consistent
* make abstract descriptive statistics (e.g. min, max, ave, etc.) by hiding statistics computation return index behind a human-legible key (e.g. `lbsStatistics.MIN` etc.)
* improve `LBAF` statistical and plain text reporting

**Comment by ppebay** [comment]
Revisiting this abandoned issue

**Comment by ppebay** [comment]
Extended the issue to include several other aspects such as:
* generalizing of the global statistics selection and mapping to respective computation methods
* formatting/documentation of algorithms that is not always consistent
* make abstract descriptive statistics (e.g. min, max, ave, etc.) by hiding statistics computation return index behind a human-legible key (e.g. `lbsStatistics.MIN` etc.)
