### ISSUE TITLE
is reading data from json file working correctly?

### ISSUE THREAD

**Issue by cz4rs** [DARMA-tasking/LB-analysis-framework#233]
Random question after analysing the code in `lbsVTDataReader.py`:

- `comm_dict` is first created at top level
https://github.com/DARMA-tasking/LB-analysis-framework/blob/f93c5aad550a283dabb8d27d55167b47ebc8b422/src/lbaf/IO/lbsVTDataReader.py#L142-L144
- then for every phase, it gets re-initialized
https://github.com/DARMA-tasking/LB-analysis-framework/blob/f93c5aad550a283dabb8d27d55167b47ebc8b422/src/lbaf/IO/lbsVTDataReader.py#L151-L156
- inside the loop the communication edges are written into it
https://github.com/DARMA-tasking/LB-analysis-framework/blob/f93c5aad550a283dabb8d27d55167b47ebc8b422/src/lbaf/IO/lbsVTDataReader.py#L188-L192
- at the end `comm_dict` is returned
https://github.com/DARMA-tasking/LB-analysis-framework/blob/f93c5aad550a283dabb8d27d55167b47ebc8b422/src/lbaf/IO/lbsVTDataReader.py#L213

As far as I understand only the data from the last phase gets returned. Is that intended / correct behavior?

**Comment by ppebay** [comment]
Thanks for spotting this @cz4rs 
In my view this is clearly a bug: the `comm_dict` should be a 2-deep dictionary, where the top-level key would be `phase_id` and the second-level keys would be the receiver/sender object IDs. 
@marcinwrobel1986 can you please fix this behavior?
Thanks

**Comment by marcinwrobel1986** [comment]
Hi, I will take a look as first thing in the morning.

**Comment by marcinwrobel1986** [comment]
@cz4rs Thanks Cezary for catching that. I checked that out and it's definiately not the correct behavior. Needs to be fixed. I am on it.
