### ISSUE TITLE
Add type field to LB data files

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/LB-analysis-framework#243]
Also, add schema for other JSON files.

**Comment by nlslatt** [comment]
The LB data json files now have `{"type":"LBDatafile","phases":[`...`]}`.

The LB statistics json files now have `{"type":"LBStatsfile","phases":[`...`]}`. The full schema for the LB statistics json files can be figured out by looking at this file (it wouldn't let me upload uncompressed): [vt_lb_statistics.2022-05-04-11-20-04.json.gz](https://github.com/DARMA-tasking/LB-analysis-framework/files/8626126/vt_lb_statistics.2022-05-04-11-20-04.json.gz)
