### ISSUE TITLE
Check brute force optimalization on data other than synthetic_lb_data

### ISSUE THREAD

**Issue by marcinwrobel1986** [DARMA-tasking/LB-analysis-framework#247]
### What is the concern?:
- While performing brute force optimalization on `synthetic_lb_data` takes about 4 seconds, performing it on other data, e.g. `4color-4node-data` takes, so long I needed to cancel execution

### TODO:
- check if steps in `brute force optimization` are optimal
- maybe try to estimate how long should it take
- check if `brute force optimization` is done correctly
- can it be done on data other than `synthetic_lb_data`

**Comment by ppebay** [comment]
Makes sense

**Comment by ppebay** [comment]
No longer needed as a result of #371
