### ISSUE TITLE
Add subphase-sensitive migration criteria

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/LB-analysis-framework#270]
Subtask of #53

As proposed in https://github.com/DARMA-tasking/vector-balancing-report

Also, based on Ronak's work

**Comment by ppebay** [comment]
Picking up this issue.

@marcinwrobel1986 do you know if we've got a dataset in the new format, that contains subphases?

**Comment by ppebay** [comment]
Ok thanks.
And the reader is ignoring the subphases? I am going to look into what it's doing exactly but any heads-up would help. Tx

**Comment by marcinwrobel1986** [comment]
yes, reader is ignoring subphases as they were never used in the code

**Comment by marcinwrobel1986** [comment]
Reading sub-phases from files will be added once #274 is merged
