### ISSUE TITLE
"time" key must be replaced with "load" for objects in JSON files

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#281]
This must also be propagated to the validation harness

Related to #279

**Comment by marcinwrobel1986** [comment]
@ppebay any answer here?

**Comment by ppebay** [comment]
Yes your interpretation is correct. Thank you and sorry for the delay.

**Comment by ppebay** [comment]
@marcinwrobel1986 quick status update?

**Comment by marcinwrobel1986** [comment]
> @marcinwrobel1986 quick status update?

@ppebay done here #293
