### ISSUE TITLE
Ensure that JSON trace files are read only once when multiple phases are sought

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#289]
Step to illustrate the problem to be solved: run the following
```
python LBAF_app.py --conf every20phases.yaml
```
in `lbaf/Applications`.

**Comment by marcinwrobel1986** [comment]
> Step to illustrate the problem to be solved: run the following
> 
> ```
> python LBAF_app.py --conf every20phases.yaml
> ```
> 
> in `lbaf/Applications`.

@ppebay I don't have the `data/nolb-8color-16nodes-every50phases/stats` data set, but it is np. I should sort it out anyway.
I will ask you when I would need that :)
