### ISSUE TITLE
Use colors to make standard output more legible

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#29]
All line preambles (contained between square brackets, e.g. `[lbsStatistics]`) should appear in a color different than that of the subsequent text.

**Comment by yaleLeeNGA** [comment]
Several colors are implemented:  
- HEADER (purple)
- BLUE
- GREEN
- WARN (orange)
- ERR (red)

providing these kinds of visuals: 
![image](https://user-images.githubusercontent.com/54635963/67103570-b2ac5300-f1c5-11e9-8113-960217a7e66c.png)
![image](https://user-images.githubusercontent.com/54635963/67103597-bdff7e80-f1c5-11e9-90f3-0044a7ae83a5.png)  

N.B.: the error messages which may be triggered while importing modules are not colored.

**Comment by yaleLeeNGA** [comment]
Windows 10 distributions may require to manually enable ANSI console colors: https://github.com/ytdl-org/youtube-dl/issues/15758#issuecomment-370206837
