### ISSUE TITLE
Add Python "linter" to CI/CD

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#320]
This is to homogenize style with respect to PEP etc.

**Comment by tlamonthezie** [comment]
There was an old integration of both pylint and coverage inside the unit-test but it has been disabled.
It seems it was at some time planned to integrate in tox. I think **Unit Test** should be renamed in **Code Quality** to prevent confusion becaus in fact this is tox not just unit tests.

**Comment by tlamonthezie** [comment]
When rendering badges this is how it has been set in latest commit
![image](https://user-images.githubusercontent.com/20086568/220159315-436eb73a-5958-40a1-95a8-6d7ab95215f9.png)
