### ISSUE TITLE
Make sure NodeGossiper does not crash when ParaView is not found

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#33]
1. We can safely assume that VTK proper remains a requirement because the VTK graph viz features we need are not part of the ParaView distributed by Kitware
2. However we can also assume that not everyone will have ParaView on their systems and in this case the NodeGossiper should still run. It should just not generate the ParaView visualizations.

**Comment by yaleLeeNGA** [comment]
Isn't this covered by issue #27?

**Comment by ppebay** [comment]
Yes somehow, so I am going to narrow down #27 to ensure these two do not overlap

**Comment by yaleLeeNGA** [comment]
@ppebay Can this one be closed then?
