### ISSUE TITLE
Automatically set n_ranks based on files found by stem

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/LB-analysis-framework#353]

**Comment by tlamonthezie** [comment]
We have to find the `n_ranks` value automatically and to remove it from the LBAF configuration
1. `n_ranks` can be found by reading input JSON data files at the following path `json_data[metadata][shared_node][num_nodes]` (considering json_data is loaded jso data). (If present in first file all files should have the same data so this is only needed to read the first data file)
2. if `n_ranks` cannot be determined from JSON file metadata the consider that n_ranks is equal to the number of data files 
3. Finally completely remove the `n_ranks` configuration parameter
