### ISSUE TITLE
Update and fix JSON VT writer

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#354]
In particular:
* phase ID is incorrect
* object rank ID assertion needed
* missing communications
* etc.

**Comment by lifflander** [comment]
Here's the sample LB data to read in and write out: 
[vt_lb_data.tar.gz](https://github.com/DARMA-tasking/LB-analysis-framework/files/10936519/vt_lb_data.tar.gz)
