### ISSUE TITLE
Replace list return types with sets wherever possible

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#359]
This is to improve performance: it is faster to iterate over set than over lists and even faster to check element ownership.

There are cases where we want to perform indexing and/or modification of the returned collection and a result in those cases lists should be conserved.

**Comment by cwschilly** [comment]
Are there specific places to change list to set, if appropriate?

**Comment by ppebay** [comment]
Resolved as discussed in now closed PR #406
