### ISSUE TITLE
Add missing elements to VT JSON writer

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#363]
This is a sequel to #354 , in particular to:
* If there was other metadata in the input file, include it here too. The `shared_node` fields may influence how a load balancer behaves, and we would definitely want to document in the output file that the load balancer was run using those assumptions.
* add communications (when available) and optional user-defined data
* please feel free @nlslatt to add anything here

**Comment by lifflander** [comment]
This will be fixed as part of the VT-TV integration effort.

**Comment by cwschilly** [comment]
Closed with #483
