### ISSUE TITLE
CI testing rendering

### ISSUE THREAD

**Issue by nmm0** [DARMA-tasking/LB-analysis-framework#371]
When we want to add ci for the vtk rendering, we may run into some issues with running the visualizer in docker with graphics driver and X display. It should be sufficient on the driver side to install a software renderer, and for the X display we can use xvfb to simulate an X display even though we don't have a physical one:

```bash
xvfb :99 -screen 0 1920x1080x24 -nolisten tcp &
export DISPLAY=:99
```

**Comment by pierrepebay** [comment]
Will be addressed in https://github.com/DARMA-tasking/vt-tv/issues/15
