### ISSUE TITLE
Investigate why acceptance test at times fails

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#375]
The `conf.yaml` test should always result in a 0-imbalance. The test parameters should be altered to ensure it always converges despite the probabilistic nature of the algorithm, while it currenly fails at times, e.g. in this [CI run](https://github.com/DARMA-tasking/LB-analysis-framework/actions/runs/4722515948/jobs/8382398068)

**Comment by tlamonthezie** [comment]
This might be because we forget to rename the-config argument to -configuration call on the workflow yaml file. (We have renamed this argument recently). So it might not use the correct config file (by default the config/conf.yaml is used so lbaf runs correctly) It will be quickly corrected in that case.

**Comment by tlamonthezie** [comment]
> This might be because we forget to rename the-config argument to -configuration call on the workflow yaml file. (We have renamed this argument recently). So it might not use the correct config file (by default the config/conf.yaml is used so lbaf runs correctly) It will be quickly corrected in that case.

After some tests this is not the reason of the problem. THe configuration file is correct. We have still to investigate

**Comment by ppebay** [comment]
Re-assigning to @cwschilly

**Comment by tlamonthezie** [comment]
We have to analyze logs from github because some run fail and other succeed when running many times.

**Comment by tlamonthezie** [comment]
We have to generate output in full debug mode. We will see in what order object transfers has occured.
We probably need to sort everything...

**Comment by tlamonthezie** [comment]
@ppebay Please find detailed log (debug level) for a failing test:
https://github.com/DARMA-tasking/LB-analysis-framework/actions/runs/5672505156/job/15371853173#step:7:45
