### ISSUE TITLE
Rework import structure in LBAF_app and other files

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#376]
1. Reorganize Import statements and PYTHONPATH

In many files some module import are done by code using the `sys.path.append` functions but it will be cleaner if we use the PYTHONPATH environment variable like this:

`export PYTHONPATH="${PYTHONPATH}:/path/to/project"`

Currently many files contains a code like the following and with the environment variable it won't be needed

https://github.com/DARMA-tasking/LB-analysis-framework/blob/3720ef281e698b31e3bee339b2e94ad83cd59a34/src/lbaf/Applications/LBAF_app.py#L11-L16

After that import statements will be correctly grouped at the top of python modules it will be cleaner and more compliant with pylint 

2. Rework setup configuration to make setup work for Python 3.9 (currently setup requires Python 3.8)

**Comment by tlamonthezie** [comment]
Today we use the LBAF application in development mode so it can be helpful if we install lbaf i editable mode.
So it will be added to requirements*.txt files
It is possible also to run directly (from the project root dir) `pip install -e .` to do that (-e means editable mode and . tells to install using setup.cfg)

After having installed lbaf in editable mode we will be able to run LBAF Application easily using an entrypoint:
![image](https://user-images.githubusercontent.com/20086568/234908677-bf782d52-c76b-4f1e-807c-894558e875da.png)

**Comment by ppebay** [comment]
@cwschilly @tlamonthezie we want to be able **without the requirement to use virtual environments** to run two or more different versions of LBAF. 

The current modus operandi based on requiring an **install** of LBAF does not seem to work for that.

What is a solution? Do we have to return to the "old mode" (pre-#381) or is there a way to do this with the current setup?

**Comment by ppebay** [comment]
@tlamonthezie we are having problems with the current setup, in that it does not seem to allow for the co-existence of several versions of LBAF on the same system (without using a virtual environment). Can you please comment on that, and if it's possible indeed, explain how to do it?

Otherwise we will need a different setup. Thanks

@lifflander @nlslatt

**Comment by tlamonthezie** [comment]
> @cwschilly @tlamonthezie we want to be able **without the requirement to use virtual environments** to run two or more different versions of LBAF.
> 
> The current modus operandi based on requiring an **install** of LBAF does not seem to work for that.
> 
> What is a solution? Do we have to return to the "old mode" (pre-#381) or is there a way to do this with the current setup?

@ppebay the current setup is based on pip so it is not possible with pip to have multiple versions of the same package on a single python environment. **The only way to do is to re-introduce the "old" mode** for this kind of usage - even if it is not compatible with pip package installation (Currently lbaf package is installed using pip in editable mode) -
**We have do do some tests because both pip and non-pip installation may be in conflict** if a user installed lbaf as a package and wants to have different versions (multiple branches for example at the same time in different local folders) he might have to uninstall the lbaf package that he installed with pip.
