### ISSUE TITLE
GitHub action passes even when Python error is raised in tox run

### ISSUE THREAD

**Issue by pierrepebay** [DARMA-tasking/LB-analysis-framework#377]
Relative import path Python error fixed in #373 was not causing the GitHub actions to be marked as failing: https://github.com/DARMA-tasking/LB-analysis-framework/actions/runs/4569049204/jobs/8064831145#step:7:1627, if other errors appear will the tox run be marked as passing as well ?

**Comment by tlamonthezie** [comment]
If a unit test is failing then the job is failing as expected (unittest fails then tox returns an error code)
https://github.com/DARMA-tasking/LB-analysis-framework/actions/runs/4807421528/jobs/8556225391

If there is a python error like invalid import it also fails
https://github.com/DARMA-tasking/LB-analysis-framework/actions/runs/4807512147/jobs/8556371469

The error was only happening with coverage run. I am trying to understand why but it seems related to how python loads packages when running coverage.
