### ISSUE TITLE
Non-blocking follow-on style and consistency post-PR358

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#379]
This is a follow-on to PR #357 as some style/consistency issues were noted (but were not blocking for said PR):
* inconsistency in naming of utility classes (in `Utils`): they should start with `lbs`, with the exception of:
  *  stand-alone scripts (no particular style required for these)
  * imported scripts that come from elsewhere
* inconsistent use of final full stop before triple quotes in docstrings
* still some occurrences of exclamation marks in error/warning outputs

All of the above should be addressed as part of this issue

Reference : https://peps.python.org/pep-0008/#package-and-module-names

**Comment by ppebay** [comment]
Alright, thanks for suggestion @tlamonthezie so please apply changes above throughout entire code base thanks.

**Comment by ppebay** [comment]
Any update on that one @tlamonthezie ?

**Comment by tlamonthezie** [comment]
> Any update on that one @tlamonthezie ?

Hello @ppebay not for the moment but soon
