### ISSUE TITLE
Print list of implemented QOIs

### ISSUE THREAD

**Issue by nlslatt** [DARMA-tasking/LB-analysis-framework#388]
If it is does not yet exist, add a command-line option to LBAF to print a list of implemented QOI. When a yaml file contains an invalid QOI, print that list as part of the error message. The current error handling approach (the Python script erroring out because a function has not been defined) is not at all user-friendly.

**Comment by ppebay** [comment]
For instance in `lbsRank` we have the following implemented QOI "getters":

```
    def get_id(self) -> int:

    def get_size(self) -> float:

    def get_shared_block_ids(self) -> set:

    def get_number_of_shared_blocks(self) -> float:

    def get_number_of_homed_blocks(self) -> float:

    def get_number_of_uprooted_blocks(self) -> float:

    def get_homed_blocks_ratio(self) -> float:

    def get_shared_memory(self):

    def get_number_of_objects(self) -> int:
```

(probably only those returning a numeric type should be considered)
