### ISSUE TITLE
Verify/Update the online documentation

### ISSUE THREAD

**Issue by cwschilly** [DARMA-tasking/LB-analysis-framework#393]

**Comment by cwschilly** [comment]
Running `JSON_data_files_validator_loader` and `vt_data_extractor.py` from the command line leads to errors. Are these still intended to be used independently by users, or are they meant to be interacted with indirectly  elsewhere in the code base? (For example, running `test_JSON_data_files_validator.py` calls the validator loader and works perfectly)

**Comment by tlamonthezie** [comment]
> Running `JSON_data_files_validator_loader` and `vt_data_extractor.py` from the command line leads to errors. Are these still intended to be used independently by users, or are they meant to be interacted with indirectly elsewhere in the code base? (For example, running `test_JSON_data_files_validator.py` calls the validator loader and works perfectly)

JSON_data_files_validator_loader cannot be currently run alone (it is called internally by the LBAF application) but it could be made runnable easily with the addition of a main function and by using absolute imports to the lbaf package. We have to create an issue for that.

**Comment by cwschilly** [comment]
I still need to update the wiki and README after resolution of #396 and #397

**Comment by stmcgovern** [comment]
After discussion, this issue concerns only the content of the documentation and the modifications to deploy docs workflow have been split off into issue #419 .

**Comment by cwschilly** [comment]
@ppebay This issue can be closed with #424
