### ISSUE TITLE
Make JSON_data_files_validator_loader.py callable from the command line

### ISSUE THREAD

**Issue by cwschilly** [DARMA-tasking/LB-analysis-framework#396]
Running the `JSON_data_files_validator_loader.py` from the command line currently throws an error:
"ImportError: attempted relative import with no known parent package"

For now, the wiki page includes directions on how to load the validator from VT using this [link](https://raw.githubusercontent.com/DARMA-tasking/vt/develop/scripts/JSON_data_files_validator.py), but it would be better to be able to run the loader instead.

**Comment by tlamonthezie** [comment]
Currently this script is not callble because has not a main entry point. This is a feature to add this.
