### ISSUE TITLE
Fix ModuleNotFoundError: No module named 'lbaf.Utils.exception_handler'

### ISSUE THREAD

**Issue by cwschilly** [DARMA-tasking/LB-analysis-framework#415]
When running `lbaf` off of the develop branch, there is an error: "`Fix ModuleNotFoundError: No module named 'lbaf.Utils.exception_handler'`"

**Comment by tlamonthezie** [comment]
The lbaf.Utils.exception_handler has been removed at #379.
We should just remove the import statement and the use of that. It is something that has been forgotten when refatoring during  work. It will be solved easily
