### ISSUE TITLE
Make lbsVTDataWriter at parity with the lbsVTDataReader for user-defined data

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/LB-analysis-framework#421]
We want the JSON data writer to write out exactly the same data that is input by the reader.

**Comment by ppebay** [comment]
In particular, what is missing from the writer is the exporting of the "user-defined" data, illustrated for example in:
```
data/user-defined-memory-toy-problem/toy_mem.0.json
```

Reading in this trace set (for instance with the phase stepper) and outputting it directly results in the `user_defined` key/value pair being entirely absent from the output.

One way to exercise this case would be to start from the following configuration file:
```
config/user-defined-memory-toy-problem.yaml
```
and to amend it to replace the load-balancer with the phase stepper.
