### ISSUE TITLE
Create a new command-line flag to specify the suffix/extension of vt trace files

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#43]
Currently we only let the user specify the prefix, and we assume that the extension is always ".vom". However vt outputs ".out" stats, which forces us to do file manipulation prior to running LBAF on those.

In order to further automate the process and therefore LBAF understand one additional and optional flag like `-e <extension>`  with a default at `''` (because there could also be no extension at all". Note that in this setting we would need to pass, e.g., `-e ".out"` and not just `-e out`.

**NB:** this means that the current `-e` (for exodus outputs) must be changed to something else: I suggest `-m` for (**M**esh outputs).

**Comment by marcinwrobel1986** [comment]
@ppebay I think this is done in #70

**Comment by ppebay** [comment]
Closing.
