### ISSUE TITLE
Add a configuration file

### ISSUE THREAD

**Issue by yaleLeeNGA** [DARMA-tasking/LB-analysis-framework#46]
Add the possibility to specify arguments in a configuration file in `yml` or `json`.

**Comment by lifflander** [comment]
@marcinwrobel1986 We want to remove the command line arguments and start using a YAML file to specify the configuration. Yale started this work, but didn't finish: https://github.com/DARMA-tasking/LB-analysis-framework/commits/46-configuration-file

**Comment by lifflander** [comment]
Also, as a side note, can we rename the file `NodeGossiper.py` to `LBAF.py`

**Comment by marcinwrobel1986** [comment]
@lifflander if you have any suggestions regarding structure, please write. If not I will get back with some proposal. Thanks.
