### ISSUE TITLE
Improve coverage

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#461]
We should aim for 75% with the following caveats:
* the visualization component will shortly be deprecated and replaced by `vt-tv` so we should not focus on it;
* the IO component is still incomplete and will ultimately disappear as we, therefore aiming for 75% on it is not desirable.

**Comment by cwschilly** [comment]
Here is the output of running coverage:



Module | statements | missing | excluded | coverage
-- | -- | -- | -- | --
src/lbaf/Applications/LBAF_app.py | 295 | 230 | 0 | 22%
src/lbaf/Applications/MoveCountsViewer.py | 211 | 193 | 0 | 9%
src/lbaf/Applications/__init__.py | 0 | 0 | 0 | 100%
src/lbaf/Execution/__init__.py | 0 | 0 | 0 | 100%
src/lbaf/Execution/lbsAlgorithmBase.py | 136 | 102 | 0 | 25%
src/lbaf/Execution/lbsBruteForceAlgorithm.py | 38 | 38 | 0 | 0%
src/lbaf/Execution/lbsCentralizedPrefixOptimizerAlgorithm.py | 160 | 160 | 0 | 0%
src/lbaf/Execution/lbsClusteringTransferStrategy.py | 89 | 77 | 0 | 13%
src/lbaf/Execution/lbsCriterionBase.py | 37 | 10 | 0 | 73%
src/lbaf/Execution/lbsInformAndTransferAlgorithm.py | 115 | 74 | 0 | 36%
src/lbaf/Execution/lbsPhaseStepperAlgorithm.py | 18 | 18 | 0 | 0%
src/lbaf/Execution/lbsRecursiveTransferStrategy.py | 107 | 71 | 0 | 34%
src/lbaf/Execution/lbsRuntime.py | 41 | 31 | 0 | 24%
src/lbaf/Execution/lbsStrictLocalizingCriterion.py | 24 | 15 | 0 | 38%
src/lbaf/Execution/lbsTemperedCriterion.py | 16 | 7 | 0 | 56%
src/lbaf/Execution/lbsTransferStrategyBase.py | 77 | 45 | 0 | 42%
src/lbaf/IO/__init__.py | 0 | 0 | 0 | 100%
src/lbaf/IO/lbsConfigurationUpgrader.py | 130 | 130 | 0 | 0%
src/lbaf/IO/lbsConfigurationValidator.py | 60 | 8 | 0 | 87%
src/lbaf/IO/lbsGridStreamer.py | 65 | 60 | 0 | 8%
src/lbaf/IO/lbsStatistics.py | 218 | 130 | 0 | 40%
src/lbaf/IO/lbsVTDataReader.py | 154 | 36 | 0 | 77%
src/lbaf/IO/lbsVTDataWriter.py | 59 | 47 | 0 | 20%
src/lbaf/IO/lbsVisualizer.py | 492 | 469 | 0 | 5%
src/lbaf/Model/__init__.py | 0 | 0 | 0 | 100%
src/lbaf/Model/lbsAffineCombinationWorkModel.py | 28 | 17 | 0 | 39%
src/lbaf/Model/lbsBlock.py | 32 | 24 | 0 | 25%
src/lbaf/Model/lbsLoadOnlyWorkModel.py | 10 | 4 | 0 | 60%
src/lbaf/Model/lbsMessage.py | 10 | 0 | 0 | 100%
src/lbaf/Model/lbsObject.py | 79 | 16 | 0 | 80%
src/lbaf/Model/lbsObjectCommunicator.py | 29 | 0 | 0 | 100%
src/lbaf/Model/lbsPhase.py | 230 | 111 | 0 | 52%
src/lbaf/Model/lbsRank.py | 122 | 38 | 0 | 69%
src/lbaf/Model/lbsWorkModelBase.py | 19 | 1 | 0 | 95%
src/lbaf/Utils/__init__.py | 0 | 0 | 0 | 100%
src/lbaf/Utils/lbsArgumentParser.py | 98 | 86 | 0 | 12%
src/lbaf/Utils/lbsColors.py | 30 | 4 | 0 | 87%
src/lbaf/Utils/lbsCsv2JsonDataConverter.py | 101 | 76 | 0 | 25%
src/lbaf/Utils/lbsDataStatFilesUpdater.py | 93 | 72 | 0 | 23%
src/lbaf/Utils/lbsJSONDataFilesValidatorLoader.py | 40 | 10 | 0 | 75%
src/lbaf/Utils/lbsLogging.py | 61 | 9 | 0 | 85%
src/lbaf/Utils/lbsPath.py | 10 | 3 | 0 | 70%
src/lbaf/Utils/lbsVTDataExtractor.py | 169 | 77 | 0 | 54%
src/lbaf/Utils/lbsWeb.py | 31 | 11 | 0 | 65%
src/lbaf/__init__.py | 31 | 10 | 0 | 68%
src/lbaf/__main__.py | 7 | 7 | 0 | 0%
src/lbaf/imported/JSON_data_files_validator.py | 125 | 11 | 0 | 91%
src/lbaf/imported/__init__.py | 0 | 0 | 0 | 100%
Total | 3897 | 2538 | 0 | 35%

**Comment by ppebay** [comment]
Some comments:
* Phase stepper is not very important as it will be superseded by `vt-tv` in stand-alone mode;
* runtime, transfer strategies, and work models should be prioritized
