### ISSUE TITLE
Odd NodeGossiper behavior when VTK missing

### ISSUE THREAD

**Issue by yaleLeeNGA** [DARMA-tasking/LB-analysis-framework#48]
When trying to run NodeGossiper without VTK, the following error message is displayed:  
```
*  ERROR: Could not write to ExodusII file by lack of VTK
```  
But still tries to get further making LBAF crash: 
```
Traceback (most recent call last):
  File "NodeGossiper.py", line 580, in <module>
    params.verbose)
  File "C:\dev\git\LBAF\src\IO\lbsWriterExodusII.py", line 118, in write
    n_p = len(self.phase.processors)
AttributeError: WriterExodusII instance has no attribute 'phase'
```

Such case should be properly handled by avoiding crashing.

**Comment by ppebay** [comment]
Please check this out

**Comment by marcinwrobel1986** [comment]
Nothing special @ppebay VTK must be present, either with Paraview site-packages or directly from PyPi. I included them in requirements.txt

**Comment by ppebay** [comment]
This is now resolved
