### ISSUE TITLE
Improve and complete JSON writing

### ISSUE THREAD

**Issue by pierrepebay** [DARMA-tasking/LB-analysis-framework#482]
The goal is to be able to have the JSON outputted by LBAF (when using the internal data structures) to be identical to the input JSON.

Missing elements at this point are (non exhaustive):
- [x] Communications
- [x] subphases
- [x] index
- [x] collection_id
- [x] shared_node data

This issue should also deprecate the use of `-1` to read/step through all phases (only explicit enumerations or ranges should be used).

**Comment by cwschilly** [comment]
@lifflander @ppebay @pierrepebay 
I have added more elements that are not being written out to the original issue. For a couple of these, I am not sure what they represent.

Specifically, what do `index` and `collection_id` refer to in the following snippet of an input JSON file?
```json
"id": 0,
      "tasks": [
        {
          "entity": {
            "collection_id": 7,
            "home": 0,
            "id": 3407875,
            "index": [
              12
            ],
            "migratable": true,
            "type": "object"
          },
```

**Comment by ppebay** [comment]
@cwschilly I think these quantities are not relevant to LBAF, but I will let @lifflander confirm this (or not)

**Comment by ppebay** [comment]
**N.B.:** the first `id` concerns the **phase**.

**Comment by cwschilly** [comment]
I am also not sure what the data in the `shared_node` block represents:

  "metadata": {
    "rank": 0,
    "shared_node": {
      "id": 0,
      "num_nodes": 1,
      "rank": 0,
      "size": 4
    },
    "type": "LBDatafile"
  },

Right now, I'm using these "conversions":

`id`: `phase.get_id()`
`num_nodes`: `rank.get_number_of_shared_blocks()`
`rank`: `rank.get_id()`
`size`: `phase.get_number_of_ranks()`

**Comment by ppebay** [comment]
@pierrepebay regarding the other fields: used in `vt-tv`, or not?
