### ISSUE TITLE
Add capability to create and export a dataset containing shared blocks

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#506]
Conceptually, this would be allow for the creation of JSON files representing such diagrams:

![Screen Shot 2024-05-03 at 5 58 07 PM](https://github.com/DARMA-tasking/LB-analysis-framework/assets/17439260/3c285ebd-9b3e-4b98-8119-f4914a783eb6)

**Comment by ppebay** [comment]
@lifflander please feel free to amend as you see fit

**Comment by lifflander** [comment]
Part of this issue is getting the JSON writer in LBAF to be able to output user-defined memory blocks.

**Comment by ppebay** [comment]
Some additional design discussion notes:

<img width="448" alt="Screenshot 2024-06-19 at 10 44 50" src="https://github.com/DARMA-tasking/LB-analysis-framework/assets/17439260/60504d08-5bf4-43e5-8068-4d31e8609554">

which yields:

<img width="1262" alt="Screenshot 2024-06-19 at 10 30 22" src="https://github.com/DARMA-tasking/LB-analysis-framework/assets/17439260/77093655-dead-4768-9b14-d83c155d0149">

and:

<img width="1137" alt="Screenshot 2024-06-19 at 10 30 03" src="https://github.com/DARMA-tasking/LB-analysis-framework/assets/17439260/bbd22092-ad3f-4655-b5dc-6dd62928f610">

**Comment by ppebay** [comment]
Reference @tlamonthezie : 
https://arxiv.org/abs/2404.16793
