### ISSUE TITLE
Update JSON generator to work with vt's `LBDataHolder`

### ISSUE THREAD

**Issue by cwschilly** [DARMA-tasking/LB-analysis-framework#527]
In order for vt to successfully encode information in an object's ID, we need to:

- [ ] Add `collection_id` to each `entity` field
- [ ] Output the entire `entity` in the `communications` to/from fields (including `home`, and `migratable`)
- [ ] Use `seq_id` instead of `id` for objects/tasks (since `id` now means that the value is encoded)
- [ ] #531 

---

As a model, vt's `LBDataHolder` has this function:

```cpp
void LBDataHolder::outputEntity(nlohmann::json& j, ElementIDStruct const& id) const {
  j["type"] = "object";
  j["id"] = id.id;
  j["home"] = id.getHomeNode();
  j["migratable"] = id.isMigratable();
  if (node_idx_.find(id) != node_idx_.end()) {
    auto const& proxy_id = std::get<0>(node_idx_.find(id)->second);
    auto const& idx_vec = std::get<1>(node_idx_.find(id)->second);
    j["collection_id"] = proxy_id;
    for (std::size_t x = 0; x < idx_vec.size(); x++) {
      j["index"][x] = idx_vec[x];
    }
  } else if (node_objgroup_.find(id) != node_objgroup_.end()) {
    auto const& proxy_id = node_objgroup_.find(id)->second;
    j["objgroup_id"] = proxy_id;
  } else {
    // bare handler
  }
}
```

which is called any time an object is being written, whether in the communications field or tasks field. For example:

```cpp
      // Adding entity to tasks
      outputEntity(j["tasks"][i]["entity"], id);
      
      // Adding entity to communications["to"] or communications["from"]
      outputEntity(j["communications"][i]["from"], key.fromObj());
      outputEntity(j["communications"][i]["to"], key.toObj());
```

**Comment by ppebay** [comment]
@cwschilly I am unsure I understand from the description, whether `seq_id` will **replace** `id`, or be **in addition** to it.

In either case, is it correct to understand`seq_id` in the same sense, as in examples such as below:
![screenshot_2024-08-18_at_18 26 40_720](https://github.com/user-attachments/assets/c3e623bd-d348-436a-953d-4a9e72a47948)
?

**Comment by cwschilly** [comment]
@ppebay `seq_id` should replace `id` in LBAF's generated JSON files. 

The convention we have landed on in vt is:
- `id` denotes a bit-encoded ID (ie it contains information regarding the object's home, migratability, and node) 
- `seq_id` is a standard integer identifier, which is what the LBAF generator creates

We'll need to update LBAF's reader in order to accommodate this change.

**Comment by ppebay** [comment]
Alright, thanks @cwschilly -- and also following discussion with @lifflander I understand that any object would now be identified via a triplet (`seq_id`, `home_id`, `migratable`) in $\mathbb{N}^2\times\mathbb{Z}_2$. 

Would it be the generator that would be then responsible for turning this triplet into a packed `id`; or that would be done by vt itself when reading a JSON using that format?

**Comment by cwschilly** [comment]
@ppebay vt will read in the plain `seq_id` and generate the packed `id` from there. This work is being done in [vt #2343](https://github.com/DARMA-tasking/vt/pull/2343)

This being said, in the future it might be advantageous for LBAF to use the same identification schema as vt. But for now, LBAF's generator is **not** responsible for packing the ids.
