### ISSUE TITLE
Setup CI using GitHub Actions for analysis framework

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/LB-analysis-framework#57]
We should set up some docker files to build containers for testing. Then we can launch those containers in GitHub Actions.

There are several levels of testing to accomplish:
* [ ] Obtain all deps (VTK, etc). for python scripts
* [ ] Run LB simulator with inputs and check it runs to end without assertion failures
* [ ] Verify simulator correctness with input decks evaluating the quality of distributions produced by LB

**Comment by ppebay** [comment]
Let's assign this issue to Marcin once he's in
