### ISSUE TITLE
Add modeling between LB stats input and strategy evaluation

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/LB-analysis-framework#58]
The vt runtime has a layer of load modeling between the raw instrumented data about each object's workload and the values used in the LB strategy implementations.

We expect this to become more critical with the strongly disparate subphase structure of execution and the load imbalances therein in EMPIRE. The load models are being used for computing a scalar load value to feed into the strategies from the vector of per-subphase loads, and we want to be able to experiment with how this ought to be done.

**Comment by ppebay** [comment]
@PhilMiller is this issue still relevant or should/could we close it?
