### ISSUE TITLE
Move all subphase developments from Braden to WIP branch

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#59]
All commits made onto develop AFTER commit 1427fc731e525c30ef69e06ba1df21bfa85192e3  (last commit from @ppebay to be included) onto develop must be moved to a new WIP branch called "subphase-support" for later inspection and revisions

**Comment by marcinwrobel1986** [comment]
I created branch [53-subphase-support](https://github.com/DARMA-tasking/LB-analysis-framework/tree/53-subphase-support) based on current develop which I believe is correct issue number.

**Comment by ppebay** [comment]
Complete
