### ISSUE TITLE
Study ordering of objects traversed during transfer phase

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/LB-analysis-framework#76]

**Comment by ppebay** [comment]
Coordinating with @nlslatt and GossipLB approach

**Comment by lifflander** [comment]
Explore ordering objects by marginal load:

> Consider the set O of objects on an overloaded process, sorted by their load in ascending order (i < j  L(O_i) < L(O_j))
>
> Compute the cumulative loads of the first k objects, C_k = sum_i 1:k O_i
>
> Find the minimum value of k for which C_k exceeds C_n - avg (i.e. the absolute overload on the process). The load of object O_k is the smallest load that the strategy will necessarily need to find space for on another process to make this process not overloaded – i.e. this is the load of the marginal object.
> 
> When shifting load off an overloaded process, it’s worth considering how the marginal load compares to the known underloaded processes, and I think this also informs the order in which processes should try to offload objects. Basically, to successfully balance the overloaded process, we’ll need to find or make a ‘hole’ of at least the size of the marginal object. Given the dynamics of the load transfer operation, I think it makes sense to try to offload the largest necessary objects first, and to target and prioritize them accordingly. I have some intuition that an approximate best-fit heuristic to pick a destination underloaded process is favorable, because that leaves space on more underloaded processes to receive larger objects.
> 
> If some overloaded process has a marginal object bigger than the largest known underload, then a fallback strategy is necessary. In this case, I believe that the best process to receive a ‘forced’ transfer that would overload it is one with much of its load made up of small objects, since that will make it easy for that process to find other hosts for its prior objects to bring its load back in line. I initially thought that a small average or median object load would be appropriate to identify this, but I can think of easy ways for bad exceptions to occur. Instead, I think we actually want to consider some quantiles of C_k, and pick one for which the new object would find the (approximate) smallest marginal load on the recipient. These quantiles would add some bulk to the gossiped data, but not a huge amount.
> 
> Given that the results in the recent paper show values for Imbalance that would still be a huge performance win to improve, and the distributed algorithms we’re working with are so fast and cheap, I think it’s very worthwhile to pay a little more to get a better result.

**Comment by PhilMiller** [comment]
The proposed first step based on that is to just do the sorting of objects on each process by load, and iterating over them first from the marginal object downward, and then upward from the object after it. This provides a principled, deterministic order.

Any changes to candidate recipients can come later.

**Comment by ppebay** [comment]
This issue has been resolved by #95
